## task
name: 'contact map generation conditioned on language description'

## train
train:
  lr: 1e-4
  batch_size: 32
  num_workers: 4
  max_steps: 100000 # max steps to train
  log_every_step: 100 # log every ${log_every_step} steps
  save_every_step: 10000 # save model every ${save_every_step} steps
  phase: 'all' # train or all
  
  resume_ckpt: '' # resume from checkpoint
  weight_decay: 0.0
  lr_anneal_steps: 0
  schedule_sampler_type: 'uniform'

## test
test:
  batch_size: 32
  num_workers: 0

## sample
sample:
  batch_size: 8
  num_workers: 0
  dataset_name: 'ContactMapExampleDataset'
  data_path: './data/examples/contact_examples.txt'
  
## dataset
dataset:
  name: 'ContactMapDataset'
  data_dir: './data'
  shuffle_seed: ${seed}
  sets: ['HumanML3D', 'HUMANISE', 'PROX'] # ['HumanML3D', 'HUMANISE', 'PROX']
  sets_config:
    HumanML3D:
      ratio: 1.0 # the ratio of the dataset to use
      load_text: true
      use_mirror: true
      use_fur: true
    HUMANISE:
      ratio: 1.0 # the ratio of the dataset to use
      load_text: true
    PROX:
      ratio: 1.0 # the ratio of the dataset to use

  data_repr: ${model.data_repr}
  data_repr_joints: [0, 10, 11, 12, 20, 21]
  use_raw_dist: false
  sigma: 0.5
  num_points: 8192
  use_color: true
  use_openscene: false
  point_feat_dim: ${model.scene_model.point_feat_dim}

  ## transforms
  train_transforms: ['RandomRotation','ApplyTransformCDM','NumpyToTensor']
  test_transforms: ['NumpyToTensor']
  transform_cfg:
    gravity_dim: 2
    random_mask_prob: 0.1

## for visualization
visualizer:
  name: 'ContactVisualizer'
  vis_joints: [0, 10, 11, 12, 20, 21]

## for evaluation
evaluator:
  name: 'ContactEvaluator'

  k_samples: 1
  num_k_samples: 10
  eval_nbatch: 100
  eval_metrics: ['dist_to_target']
  dist_to_target_thresholds: [0.1, 0.3, 0.5]
  save_results: true
