## task
name: 'motion generation conditioned on contact map and language description'

## train
train:
  lr: 1e-4
  batch_size: 32
  num_workers: 4
  max_steps: 100000 # max steps to train
  log_every_step: 100 # log every ${log_every_step} steps
  save_every_step: 10000 # save model every ${save_every_step} steps
  phase: 'train' # train or all

  resume_ckpt: '' # resume from checkpoint
  weight_decay: 0.0
  lr_anneal_steps: 0
  schedule_sampler_type: 'uniform'

## test
test:
  batch_size: 32
  num_workers: 0
  contact_folder: ''

## sample
sample:
  batch_size: 8
  num_workers: 0
  dataset_name: 'ContactMotionHumanML3DExampleDataset'
  data_path: './data/examples/h3d_examples.txt'
  contact_folder: ''

## dataset
dataset:
  name: 'ContactMotionHumanML3DDataset'
  data_dir: './data'
  shuffle_seed: ${seed}
  
  data_repr: ${model.data_repr}
  contact_type: ${model.contact_model.contact_type}
  contact_joints: ${model.contact_model.contact_joints}
  use_raw_dist: false
  sigma: 0.5
  num_points: 8192
  min_horizon: 40
  max_horizon: 196
  mix_train_ratio: 0.5

  ## transforms
  train_transforms: ['NumpyToTensor']
  test_transforms: ['NumpyToTensor']
  transform_cfg:
    gravity_dim: 1
    random_mask_prob: 0.1
    random_mask_prob_pc: 0.1
  
## for visualization
visualizer:
  name: 'ContactMotionVisualizer'
  njoints: 22

## for evaluation
evaluator:
  name: 'Text2MotionInSceneHumanML3DEvaluator'
  njoints: 22

  k_samples: 0
  num_k_samples: 128
  eval_nbatch: 32
  eval_metrics: []
  save_results: true
